# Generated by Django 5.2.6 on 2025-09-22 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_colleges', to=settings.AUTH_USER_MODEL),
        ),
    ]
